# Discovery Server Access
spring:
  application:
    sign-in-key: 'MIICWwIBAAKBgGtQ4ylb/cc2fez21oSEisr95JdurRnz/xcW4dja3zePJmRp7sFjYqv52x4Hc+n9YSeOYMGZ2QwzItDkBPzyDOVCE/eTX2a3fEYqNGiNWUTYJvtywM6SGHvgtJ97w4sL4/YlAk6V1xdO6Ea+89IxuHrKFiCDoGmMrtdjyz7JDmmHAgMBAAECgYAiE+Z+vLqCpxgnxl5qaFhWi3cqazfGtQd9AoQnQ6F8WBW97zGk8XVk3Quqpn01gYN3dyvcbolQ6XAV20KGPCrBumubAUAXJjoxmmK8RmWSc5EJpvaaNwQ35Jp2lxtL0VzLQYVxuLWRaokvNogPQUEIjo17W8/kTqsZmukFGg6p2QJBAM8n7FXF+kg4fTTTaQ=='
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/