# Discovery Server Access
spring:
  application:
    sign-in-key: 'diego'
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/