spring:
  cloud:
      config:
        uri: http://localhost:8888
        username: '{cipher}ff0ee941fc08c3283d9bff7d746ceef0e8cdea348048e3e44714ae6f44616016'
        password: '{cipher}8b3a026aefbef1c248ae19590703756a7882aa50611eccc5dbd346cfe4907fa1'
server:
  port: 8760
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
