spring:
  cloud:
    config:
      name: common-service-properties
# Discovery Server Access
zuul:
  routes:
    greetings:
      path: /greeting/**
      serviceId: greeting-service
      stripPrefix: false
eureka:
  client:
    registerWithEureka: false
    #serviceUrl:
      #defaultZone: http://localhost:8760/eureka/

server:
  port: 8080   # HTTP (Tomcat) port